name: frontend_app_flutter
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_bloc: ^8.0.0
  toggle_switch: ^2.1.0 
  google_maps_flutter: ^2.6.0
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  flutter_svg: ^2.0.10+1
  record: ^5.0.4  
  path_provider: ^2.1.2  
  line_awesome_flutter: ^2.0.0  
  fluttercontactpicker: ^4.7.0  
  shared_preferences: ^2.2.2
  awesome_snackbar_content: ^0.1.3  
  audio_waveforms: ^1.0.5
  file_picker: ^6.2.0
  connectivity: ^3.0.6
  flutter_sound: ^9.2.6
  permission_handler:  ^9.2.0
  custom_info_window: ^1.0.1
  image_picker: ^0.8.7+1
  url_launcher: ^6.2.5
  geolocator: ^7.6.2
  flutter_launcher_icons: "^0.9.0"
  audioplayers: ^6.0.0
  socket_io_client: ^2.0.3+1
  provider: ^6.1.2
  intl: ^0.18.1
  just_audio: ^0.9.38
  dio: ^5.4.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "assets/icons/icon.png" 
  android: true
  ios: true


flutter:

  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/icons/icon.png
    - assets/images/homeinvasion.jpg
    - assets/images/fireextinguisher.jpg
    - assets/images/medicalhelp.jpg
    - assets/images/travelemergency.png
    - assets/images/help.png
    - assets/images/profile_pic.jpeg
    - assets/ca/lets-encrypt-r3.pem
    - assets/images/svg/error.svg
    - assets/images/svg/bubbles.svg
    - assets/images/svg/fail.svg
    - assets/images/svg/close.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf      

